# (macos and linux: ~/.config/rio/config.toml)
# (windows: C:\Users\USER\AppData\Local\rio\config.toml)
    padding-x = 0
    padding-y = [0,0]
    line-height = 1
    hide-mouse-when-typing = true
    ignore-selection-foreground-color = true
    confirm-before-quit = false
    #working-dir = "d:"

[cursor]
    shape = 'block'
    blinking = false

#[shell]
  #program = "nu"
  #args = [""]

[render]
    performance = "Low"
    backend = "Automatic"
    disable-unfocused-render=false
    max-fps=60

[window]
    width = 1000
    height = 600
    mode = "Windowed"
    opacity=1
    blur=true
    decorations = "Buttonless"

[fonts]
extras = [{ family = "文泉驿正黑" }]
size = 20
[fonts.regular]
family = "SauceCodePro Nerd Font Mono"
style = "Normal"
weight = 400
[fonts.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Normal"
weight = 800
[fonts.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"
weight = 400
[fonts.bold-italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"
weight = 800

[navigation]
# TopTab Plain BottomTab CollapsedTab NativeTab(Macos)
mode = "CollapsedTab"
clickable = false
use-current-path = false
color-automation = []

[developer]
log-level = "OFF"

[bindings]
keys = [
    { key = "u", with = "Alt | Shift", action = "Scroll(3)"},
    { key = "d", with = "Alt | Shift", action = "Scroll(-3)"},
    { key = "u", with = "Control | Shift", action = "ScrollHalfPageUp"},
    { key = "d", with = "Control | Shift", action = "ScrollHalfPageDown"},
    
    { key = "a", with = "Alt | Shift", action = "IncreaseFontSize"},
    { key = "z", with = "Alt | Shift", action = "DecreaseFontSize"},
    { key = "r", with = "Alt | Shift", action = "ResetFontSize"},
    
    { key = "v", with = "Alt", action = "Paste"},
    { key = "c", with = "Alt", action = "Copy"},
    { key = "g", with = "Alt|Shift", action = "ToggleVIMode"},
    
    { key = "o", with = "Alt | Shift", action = "CreateTab"},
    { key = "n", with = "Alt | Shift", action = "SelectNextTab"},
    { key = "p", with = "Alt | Shift", action = "SelectPrevTab"},
    { key = "w", with = "Alt | Shift", action = "CloseTab"},
    { key = "q", with = "Alt | Shift", action = "CloseUnfocusedTabs"},
    
    
    
    { key = "k", with = "Alt | Shift", action = "SelectNextSplit"},
    { key = "j", with = "Alt | Shift", action = "SelectPrevSplit"},
    { key = "v", with = "Alt | Shift", action = "SplitRigh"},
    { key = "s", with = "Alt | Shift", action = "SplitDown"},
    { key = "c", with = "Alt | Shift", action = "CloseSplitOrTab"},
    
    { key = "f", with = "Alt | Shift", action = "SearchBackward"},
    { key = "b", with = "Alt | Shift", action = "SearchForward"},
    #{ key = "s", with = "Alt", text = "\u003A\u0077\u0071\u000D" },
]

[colors]
# Navigation
tabs            = '#494c62'
tabs-active     = '#6a6e8e'
tabs-foreground = '#1d202f'
tabs-active-highlight  = '#6a6e8e'
tabs-active-foreground = '#1d202f'
bar = '#494c62'

background = '#303446'
foreground = '#c6d0f5'
selection-background = '#626880'
selection-foreground = '#c6d0f5'

vi-cursor = '#626880'
cursor = '#626880'
# Search
search-match-background = '#626880'# 未选中颜色
search-match-foreground = '#ffffff'# 前景色
search-focused-match-background = '#ff6a19'# 当前颜色
search-focused-match-foreground = '#FFFFFF'# 背景色

black = '#51576d'
red = '#e78284'
green = '#a6d189'
yellow = '#e5c890'
blue = '#8caaee'
magenta = '#f4b8e4'
cyan = '#81c8be'
white = '#a5adce'

light_black = '#626880'
light_red = '#e67172'
light_green = '#8ec772'
light_yellow = '#d9ba73'
light_blue = '#7b9ef0'
light_magenta = '#f2a4db'
light_cyan = '#5abfb5'
light_white = '#b5bfe2'
