# (macos and linux: ~/.config/rio/themes/dracula.toml)
# (windows: C:\Users\USER\AppData\Local\rio\themes\dracula.toml)
cursor = '▇'
    padding-x = 0
    line-height = 1
    blinking-cursor = false
    hide-cursor-when-typing = true
    ignore_theme_selection_fg_color = false
    confirm-before-quit = false
    #working-dir = "d:"

[window]
    width = 1080
    height = 680
    mode = "Windowed"
    opacity=1
    blur=true

[render]
    performance = "Low"
    backend = "GL"
    disable-unfocused-render=false

[fonts]
size = 20
[fonts.regular]
family = "SauceCodePro Nerd Font Mono"
style = "normal"
weight = 400

[fonts.bold]
family = "SauceCodePro Nerd Font Mono"
style = "normal"
weight = 800

[fonts.italic]
family = "SauceCodePro Nerd Font Mono"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "SauceCodePro Nerd Font Mono"
style = "italic"
weight = 800
extras = [{ family = "新宋体" }]

[navigation]
mode = "BottomTab"
clickable = false
use-current-path = false
color-automation = []

[developer]
log-level = "OFF"

[colors]
tabs             = '#49556A'
tabs-active      = '#68A0E1'
background = '#24283b'
foreground = '#c0caf5'
selection-background = '#364a82'
selection-foreground = '#c0caf5'
cursor = '#c0caf5'
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
light_black = '#414868'
light_red = '#f7768e'
light_green = '#9ece6a'
light_yellow = '#e0af68'
light_blue = '#7aa2f7'
light_magenta = '#bb9af7'
light_cyan = '#7dcfff'
light_white = '#c0caf5'

[bindings]
  keys = [
    { key = "u", with = "Alt | Shift", action = "Scroll(3)"},
    { key = "d", with = "Alt | Shift", action = "Scroll(-3)"},
    
    { key = "u", with = "Control | Shift", action = "ScrollHalfPageUp"},
    { key = "d", with = "Control | Shift", action = "ScrollHalfPageDown"},

    { key = "a", with = "Alt | Shift", action = "IncreaseFontSize"},
    { key = "z", with = "Alt | Shift", action = "DecreaseFontSize"},
    { key = "r", with = "Alt | Shift", action = "ResetFontSize"},

    { key = "v", with = "Control | Shift", action = "Paste"},
    { key = "c", with = "Control | Shift", action = "Copy"},
    { key = "v", with = "Alt", action = "Paste"},
    { key = "c", with = "Alt", action = "Copy"},

    { key = "g", with = "Alt|Shift", action = "ToggleVIMode"},

    { key = "o", with = "Alt | Shift", action = "CreateTab"},
    { key = "c", with = "Alt | Shift", action = "CloseTab"},
    { key = "x", with = "Alt | Shift", action = "CloseTab"},

    { key = "p", with = "Alt | Shift", action = "SelectPrevTab"},
    { key = "n", with = "Alt | Shift", action = "SelectNextTab"},
    { key = "s", with = "Alt | Shift", action = "SplitHorizontally"},
    { key = "v", with = "Alt | Shift", action = "SplitVertically"},
    { key = "b", with = "Alt | Shift", action = "ClosePane"},
]

#[shell]
  #program = "nu"
  #args = [""]
