#!/bin/bash
grep "proxy" ~/.zshrc >/dev/null
if [ $? -eq 0 ]; then
    sed -i '/proxy/d' ~/.zshrc
else
    echo 'export http_proxy="http://192.168.49.1:8282"' >> ~/.zshrc
    echo 'export https_proxy="http://192.168.49.1:8282"' >> ~/.zshrc
fi

sudo grep "Acquire" /etc/apt/apt.conf >/dev/null
if [ $? -eq 0 ]; then
    sudo sed -i '/Acquire/d' /etc/apt/apt.conf
else
    sudo echo 'Acquire::http::Proxy "http://192.168.49.1:8282";' >> /etc/apt/apt.conf
fi

sudo systemctl restart networking.service

