[main]

# shell=/bin/fish
initial-window-size-chars=100x30
initial-color-theme=dark
# maximized=yes # 是否启动时最大化
# fullscreen=yes # 是否全屏启动

resize-by-cells=no
resize-keep-grid=no
resize-delay-ms=0

font=SauceCodePro NFM:size=15
box-drawings-uses-font-glyphs=yes

[cursor]
style=block
blink=no # 闪烁
blink-rate=500 # 闪烁时间(ms)

[mouse]
hide-when-typing=yes
#alternate-scroll-mode=yes # 中键粘贴

[scrollback]
lines=5000 # 保存多少行历史
multiplier=3 # 鼠标滚轮速度

[csd]
preferred=none # Wayland下推荐关闭

[bell]
urgent=no # 禁用响铃
notify=no # 视觉提示

[security]
osc52=enabled  # disabled|copy-enabled|paste-enabled|enabled

[key-bindings]
spawn-terminal=none
unicode-input=none
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

font-increase=Shift+Alt+a
font-decrease=Alt+Shift+z
font-reset=Alt+Shift+r
fullscreen=Alt+Return

scrollback-up-line=Shift+Alt+u
scrollback-down-line=Shift+Alt+d
scrollback-up-page=Control+Shift+u
scrollback-down-page=Control+Shift+d

search-start=Shift+Alt+g # 搜索滚动缓存
[search-bindings]
find-prev=Control+p
find-next=Control+n
cancel=Control+g Control+c Escape
[search-bindings]
# commit=Return KP_Enter
# cursor-left=Left Control+b
# cursor-left-word=Control+Left Mod1+b
# cursor-right=Right Control+f
# cursor-right-word=Control+Right Mod1+f
# cursor-home=Home Control+a
# cursor-end=End Control+e
# delete-prev=BackSpace
# delete-prev-word=Mod1+BackSpace Control+BackSpace
# delete-next=Delete
# delete-next-word=Mod1+d Control+Delete
# delete-to-start=Control+u
# delete-to-end=Control+k
# extend-char=Shift+Right
# extend-to-word-boundary=Control+w Control+Shift+Right
# extend-to-next-whitespace=Control+Shift+w
# extend-line-down=Shift+Down
# extend-backward-char=Shift+Left
# extend-backward-to-word-boundary=Control+Shift+Left
# extend-backward-to-next-whitespace=none
# extend-line-up=Shift+Up
# clipboard-paste=Control+v Control+Shift+v Control+y XF86Paste
# primary-paste=Shift+Insert
# unicode-input=none
# scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
# scrollback-up-half-page=none
# scrollback-up-line=none
# scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down
# scrollback-down-half-page=none
# scrollback-down-line=none
# scrollback-home=none
# scrollback-end=none

[colors-dark]
alpha=1
regular0=51576d
regular1=e78284
regular2=a6d189
regular3=e5c890
regular4=8caaee
regular5=f4b8e4
regular6=81c8be
regular7=a5adce

bright0=626880
bright1=e67172
bright2=8ec772
bright3=d9ba73
bright4=7b9ef0
bright5=f2a4db
bright6=5abfb5
bright7=b5bfe2

cursor=c6d0f5 626880 #fg bg
background=303446
foreground=c6d0f5
selection-foreground=c6d0f5
selection-background=414559
search-box-match=ffffff 626880   #fg bg
search-box-no-match=ffffff ff6a19

[environment]
TERM=xterm-256color # 设置终端类型

